SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS,
       ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO A JOIN REST_REVIEW B
USING (REST_ID)
WHERE A.ADDRESS LIKE '서울%'
GROUP BY A.REST_NAME
ORDER BY SCORE DESC, A.FAVORITES DESC